### ISSUE TITLE
Remember  dahsboard setup

### ISSUE THREAD

**Issue by sanmanmehta** [xiaohk/stickyland#11]
Does the setup persist?  I tried saving and closing after arranging every cell but with reopening of the jupyterlab, it does not persist. In other words, I have to re-arrange everything. It would be great if it remembered my dashboard setup.

**Comment by xiaohk** [comment]
Thanks for the feature suggestion! I love this idea, but I don't have the bandwidth to implement it right now. StickyLand welcomes contributions. I will close the issue for now.
