### ISSUE TITLE
feature request: floating cells outside of browser window

### ISSUE THREAD

**Issue by nyck33** [xiaohk/stickyland#14]
It would be great if I could click and drag a sticky cell outside the browser window on to my second monitor so I can scroll through the notebook while viewing my dataframe or graph.  Is this something that is possible or you might consider?

**Comment by xiaohk** [comment]
Very cool idea! One potential approach is to open the sticky window in a separate tab, but implementing it would require a lot of engineering effort. I will close issue for now. Open to PR from the community!
