### ISSUE TITLE
Is jupyterlab upper version pin correct?

### ISSUE THREAD

**Issue by DManowitz** [xiaohk/stickyland#15]
This package pins the upper version of jupyterlab as <=3.6.4.  However, additional versions of jupyterlab <4 have been released.  Does this package work with them?  If so, perhaps the upper pin should be <4, instead.

**Comment by xiaohk** [comment]
Thanks for trying the package! Unfortunately, JupyterLab 4.0 introduced a lot of breaking changes to the extension APIs. StickyLand only supports <= 3.6.4. I left a note in README. I will take a look and add support to 4.0 when I have time. 🙏

> [!NOTE]  
> StickyLand only supports JupyterLab <= 3.6.4. In June 2023, JupyterLab 4.0 was released with a lot of breaking changes. I will update StickyLand to support JupyterLab 4.0 when the official extension documentation is more polished. Any contribution to the [lab4](https://github.com/xiaohk/stickyland/tree/lab4) branch is greatly appreciated!

**Comment by DManowitz** [comment]
I'm **not** asking about Jupyterlab 4.x.  There are now versions **3.6.5** and **3.6.6** of Jupyterlab.  These are the versions I'm asking about.

**Comment by xiaohk** [comment]
Good catch! Thank you so much @DManowitz! I have updated the version and released a new version [0.2.4](https://pypi.org/project/jupyterlab-stickyland/0.2.4/).
