### ISSUE TITLE
request: Dashboard settings save?

### ISSUE THREAD

**Issue by laixuanthoi** [xiaohk/stickyland#5]
I love sticky and a request a feature is saving dashboard?

**Comment by xiaohk** [comment]
Hello @laixuanthoi, thank you so much!! Nice suggestion! We have briefly considered it. It is technically achievable: (1) we just need to save the position, size, content of all floating cells in a configuration file (e.g., json file); (2) Re-create these floating cells with the configuration file when a user clicks a button. 

We decided not to implement this feature for now. The goal of StickyLand is to empower users to organize cells in non-linear ways **during the data exploration**. Sticky cells make it super easy to create a dashboard on-the-go to enhance data exploration. However, to make product/publication-ready dashboards, there are some other better suited extensions.

We highly recommend to check out [Voila GridStackJS](https://github.com/voila-dashboards/voila-gridstack) and [ipyflex](https://github.com/trungleduc/ipyflex)! They were explicitly designed to create interactive dashboard from JupyterLab.
