### ISSUE TITLE
extemely fast video

### ISSUE THREAD

**Issue by salama4ai** [xiaohk/stickyland#6]
the illustration video is extremely fast, at level that no one can see what happens and what clicked

**Comment by xiaohk** [comment]
Hello @salama4ai, we are very sorry! Yeah the video looks extremely fast. We had to speed up the demo video to meet GitHub's 10MB gif/video requirement. 😕

You can see the original demo video on [YouTube](https://youtu.be/OKaPmEBzEX0), or click the `show details` below the fast demo video to see videos in normal speed:

https://user-images.githubusercontent.com/15007159/159070705-4160a9a8-e43a-44d0-9e89-5a7d50fca31e.mp4
