### ISSUE TITLE
Unable to resize long vertical floating cells

### ISSUE THREAD

**Issue by edwintyh** [xiaohk/stickyland#8]
Typically cell resizing can be done by dragging the bottom right corner, however for long vertical cell, the bottom right is "hidden" and "unreachable". Scrolling to the end of the Jupyter Notebook does not help.
![image](https://user-images.githubusercontent.com/45237047/159131130-88e73e7c-ae26-4f79-bd16-8fc9b338c2c8.png)
Is there any quick solution for this?

A possible longer term solution might be to allow users to resize cells based on input height and width.
The ability to define the exact height and width can help with aesthetics of dashboard design as well.

**Comment by xiaohk** [comment]
Good catch!! Sorry I didn't discover this edge case earlier.

Nice suggestion on configuring the floating cell's size directly. It is a bit complex, so for now I just always bound the floating cell's size by the screen size.

The [new release v0.2.1](https://github.com/xiaohk/stickyland/releases/tag/v0.2.1) fixed this issue:

- If a cell is too large, its floating cell will be automatically resized to fit the screen size
- Users cannot drag floating cell out of the screen
- Users cannot resize the floating cell out of the screen 

https://user-images.githubusercontent.com/15007159/160261540-db4326a9-6d16-442e-9c58-1f84d17e2058.mp4
