### ISSUE TITLE
Style:When overlap with top panel in Jupyterlab,it is hard to choose and drag it down

### ISSUE THREAD

**Issue by DatumWorld** [xiaohk/stickyland#9]
It is nice and easy to use.

Description:
1 When overlap with top panel in Jupyterlab3(where the blue box is) ,it is hard to choose and drag it down, I have to reload the current notebook.
2 The tools in right upper corner of the cell do not hide behind it when scrolling across. The tools in red box should be owned by the cell
![C6C72FCD4EBF38037ED2255901118FDE](https://user-images.githubusercontent.com/24842100/170458521-b7d03760-4462-4cd6-bb56-d48e92e38d65.jpg)
Envs:
win 10/2019，Chrome 102, Jupyterlab3.4.2 and the current stickyland 0.2.1

**Comment by xiaohk** [comment]
Hello @DatumWorld, thank you so much for raising this issue! I didn't know Jupyter Lab's new version added a cool contextual menu bar!

5da22c3598c32c2992571f0b75124b1593921bf7 should fix these two issues. You can try it by installing `jupyterlab_stickyland==0.2.2`.

https://user-images.githubusercontent.com/15007159/170907893-013d9425-3126-41cc-afa3-87a3f2ee2768.mp4

I will close the issue for now. Let me know if you have any other question.
